#!/bin/bash

#echo "Usage: proceed-file <dir> <file-without-extension> <format>"

dir=$1
file=$2
report=Report.fr
faReport=report.txt

if [ "$4" == "limits" ];
then
	limitsOption="-l $5 $6"
	echo "  i Enabling option $limitsOption"
fi

if [ "$3" == "myza" ];
then 
	filedsf=$file.dsf
	filedat=$file.dat

	fullname=$dir$filedsf

	echo "  + Coping $fullname..."
	cp $fullname .
	echo "  + Running Faildows tool..."
	wine dsf2dat.exe $filedsf

	echo "  + Creating plain data..."
	./flux-analysis -f $filedat -F myza -t "DATA-plain.txt" $limitsOption -u 6 -o "DATA.bin" -r -0.005 -K 30 -z +4 >> log.log

	echo "  + Filtering..."
	./flux-analysis -i DATA.bin -t DATA.txt -n 1.8 2 -S "config-myza.cfg" -s "DATA-strikes.txt" -M "hist.txt" -K 340 -z +4 -R $faReport  $limitsOption >> log.log

	echo "  + Plotting E(t) graph with gnuplot..."
	cat plot-graph.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp
	gnuplot plot-current.gp >> log.log 2>&1

	echo "  + Plotting histogram with gnuplot..."
	cat plot-hist.pattern | sed s/"#FILENAME#"/$file/ | sed s/"#DATETIME#"/$file/ > plot-current.gp

	gnuplot plot-current.gp >> log.log 2>&1
	
	count=`cat $faReport`
	if [ "$count" !=  "0" ];
	then
		echo "In $file founded: $count" >> Report.fr
	fi
	
elif [ "$3" == "ipf" ];
then
	echo "hh"
else
	echo "    Invalid file format specified."
fi
