#!/bin/bash

directory=$1
format=$2
listfile=$3

echo "Starting log at `date`." | tee log.log

for line in `cat $listfile`
do
    echo "* Proceeding file $line from Myza:" | tee -a log.log
    echo "----------------------------------" | tee -a log.log
    echo "For $line: " | tee -a log.log
    ./proceed-file $directory $line $format
    if [ "$?" != "0" ];
    then
        echo "! Stopping." | tee -a log.log
        exit -1
    fi
    echo "* Cleaning..."
    rm -f *.dsf *.dat *.bin *.gp *.efm DATA-plain.txt DATA-strikes.txt DATA-filtered.txt
done

