#!/bin/bash

listfile=list.lst

echo "Starting log..." > log.log

for line in `cat $listfile`
do
	echo "* Proceeding file $line:"
	echo "     " >> log.log
	echo "For $line: " >> log.log
	./proceed-file ./2012/Myza_2012/ $line
	echo "* Cleaning..."
	./clean
done

